name: docker

on:
  push:
    branches:
      - enh/40/dockerpull
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Tree view
      run: |
          ls -la
          sudo apt-get install -y tree
          tree .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DH_username }}
        password: ${{ secrets.DH_password }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: utkarsh55/demo4:v4
        file: ./Dockerfile

    - name: Pull Docker Image
      run: docker pull utkarsh55/demo4:v4

    - name: Run Docker Container
      run: docker run -p 5000:5000 utkarsh55/demo4:v4 mlflow server --host localhost --port 5000