name: docker

on:
  push:
    branches:
      - enh/40/dockerpull
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Tree view
      run: |
          ls -la
          sudo apt-get install -y tree
          tree .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DH_username }}
        password: ${{ secrets.DH_password }}

    - name: Pull Docker Image
      run: docker pull utkarsh55/demo4:v4

    - name: Run Docker Container
      run: |
        mlflow ui --host 0.0.0.0 --port 5000
        docker run -p 5000:5000 utkarsh55/demo4:v4
