name: Functional_test

on:
  pull_request:
    branches:
      - main

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mle-dev
          environment-file: env.yml
          auto-activate-base: false

      - name: Verify Conda Installation
        run: conda info


      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install tree -y

      - name: Display Directory Tree Before Building
        run: tree .

      

      - name: Build Package
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build
          python -m build

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myartifact
          path: dist/*.whl

      - name: Run main.py
        run: python src/mypackage.py
  
      - name: Display Directory Tree After Building
        run: tree .
      - name: Run Pytest
        run: pytest 

 

     