name: Functional_test
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}
        steps:
             - name: Checkout Repo
               uses: actions/checkout@v4
             - name: Setup Miniconda
               uses: conda-incubator/setup-miniconda@v3
               with:
                 activate-environment: mle-dev
                 environment-file: env.yml
                 auto-activate-base: false
             - run: |
                    sudo apt install tree
                    pip install pytest
                    pip install setuptools
                    pip install build

             - name: Before Build
               run: tree

             - name: Build package
               run: python -m build

             - name: Install Package
               run: pip install dist/mypackage-0.0.1-py3-none-any.whl

             - name: Functional Testing
               run: pytest

             - name: Run main.py
               run: python scripts/main.py

             - name: After Build
               run: tree