name: Html

on:
  pull_request:
    branches:
      - main

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mle-dev
          environment-file: deploy/conda/env.yml
          auto-activate-base: false

      - name: Verify Conda Installation
        run: conda info


      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install tree -y

      - name: Display Directory Tree Before Building
        run: tree .

      

      - name: Build Package
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build
          pip install -e .
          python -m build

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myartifact
          path: dist/*.whl
      
      - name: Download Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: myartifact   
  
      - name: Run scripy_ingest.py
        run: python script/ingest.py
          
      - name: Run script_train.py
        run: python script/script_train.py

      - name: Run script_score.py
        run: |
          python script/script_score.py 

      
      - name: Pytest functional
        run: pytest
      
      - name: Making html
        run: |
         cd docs 
         make html
      - name: Display Directory Tree After Building
        run: tree .
     
 

     